# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('qq', models.IntegerField()),
            ],
        ),
    ]
