# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20170910_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='fans',
            field=models.ManyToManyField(through='repository.UserFans', to='repository.UserInfo', verbose_name='粉丝们'),
        ),
    ]
