# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20170910_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_type', models.CharField(max_length=32, verbose_name='文章类型')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ArticleType', verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Category', verbose_name='文章分类'),
        ),
    ]
