# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_auto_20170924_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletype',
            old_name='article_type',
            new_name='type',
        ),
    ]
