# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_auto_20170924_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_detail', to='repository.Article', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='default', null=True, upload_to='', verbose_name='头像'),
        ),
    ]
