# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171216_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_access_change_password', '可以访问密码修改页'), ('can_change_own_password', '可以修改自己的密码')), 'verbose_name_plural': '账户表'},
        ),
    ]
