# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20180109_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_info',
            field=models.ForeignKey(blank=True, help_text='学员报名成功之后，方可为其创建账户！', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='学员信息'),
        ),
    ]
