# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_networkdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='user_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='1111', max_length=64, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='111', max_length=64, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_type_id',
            field=models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.IDC', verbose_name='IDC机房'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(blank=True, to='repository.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='assetrecord',
            name='asset_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar', to='repository.Asset'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='repository.Server'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='repository.Server'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='repository.Server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.Asset', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=128, unique=True, verbose_name='主机名'),
        ),
        migrations.DeleteModel(
            name='AdminInfo',
        ),
    ]
