# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180303_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='web.Host', verbose_name='绑定的主机'),
        ),
    ]
