# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180310_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.SmallIntegerField(choices=[(0, 'cmd'), (1, 'file_transfer')], verbose_name='批量任务类型')),
                ('content', models.TextField(verbose_name='批量任务内容')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='批量任务创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='批量任务执行者')),
            ],
            options={
                'verbose_name_plural': '批量任务记录',
            },
        ),
        migrations.CreateModel(
            name='MultiTaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='执行结果')),
                ('status', models.SmallIntegerField(choices=[(0, 'init'), (1, 'success'), (2, 'failed')], verbose_name='执行状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='执行任务创建时间')),
                ('end_time', models.DateTimeField(auto_now=True, null=True, verbose_name='执行任务终止时间')),
                ('bind_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BindHost', verbose_name='对应执行主机')),
                ('multi_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.MultiTask', verbose_name='批量任务')),
            ],
            options={
                'verbose_name_plural': '批量任务详细信息',
            },
        ),
        migrations.AlterUniqueTogether(
            name='multitaskdetail',
            unique_together=set([('multi_task', 'bind_host')]),
        ),
    ]
