# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180325_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitaskdetail',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行任务终止时间'),
        ),
    ]
