# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fans',
            field=models.ManyToManyField(null=True, through='repository.UserFans', to='repository.UserInfo', verbose_name='粉丝们'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=32, null=True, verbose_name='昵称'),
        ),
    ]
