# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_auto_20171029_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.BooleanField(default=0, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fans',
            field=models.ManyToManyField(related_name='f', through='repository.UserFans', to='repository.UserInfo', verbose_name='粉丝们'),
        ),
    ]
