# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171221_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_access_sales_index', '可以访问销售首页'), ('can_access_customer_table', '可以访问kind_admin下注册的客户库'), ('can_access_customer_add', '可以访问在kind_admin下注册的客户库添加客户页面'), ('can_add_customer', '可以在kind_admin下注册的客户库添加客户'), ('can_access_customer_change', '可以访问在kind_admin下注册的客户修改页'), ('can_access_change_password', '可以访问密码修改页'), ('can_change_own_password', '可以修改自己的密码')), 'verbose_name_plural': '账户表'},
        ),
    ]
